name: haskell-http-example
version: 0.1.0.0
github: "ndrewnee/haskell-http-example"
license: BSD3
author: "ndrewnee"
maintainer: "example@example.com"
copyright: "2019 ndrewnee"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/ndrewnee/haskell-http-example#readme>

dependencies:
  - base >= 4.7 && < 5
  - http-types
  - wai
  - warp
  - bytestring
  - raw-strings-qq
  - utf8-string
  - optparse-applicative

library:
  source-dirs: src

executables:
  haskell-http-example-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - haskell-http-example

tests:
  haskell-http-example-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - haskell-http-example
